# Generated by Django 3.1.1 on 2021-05-04 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('industry', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenderRef', models.CharField(max_length=300, null=True)),
                ('tenderTitle', models.CharField(max_length=300, null=True)),
                ('tenderDescription', models.TextField(max_length=1000)),
                ('openDate', models.DateTimeField(null=True)),
                ('closeDate', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('0', 'Open'), ('1', 'Active'), ('2', 'Completed'), ('3', 'Cancelled'), ('4', 'Visible')], default=2, max_length=100, null=True)),
                ('document', models.FileField(null=True, upload_to='media')),
                ('documentDescription', models.TextField(max_length=1000)),
                ('documentName', models.CharField(max_length=100, null=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industry.industry')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
